server:
  port: 8084

spring:
  application:
    name: apiGateway

  cloud:
    gateway:
      routes:
        - id: USERSERVICES
          uri: lb://USERSERVICES
          predicates:
            - Path=/users/**

        - id: HOTELSERVICES
          uri: lb://HOTELSERVICES
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATINGSERVICES
          uri: lb://RATINGSERVICES
          predicates:
            - Path=/ratings/**

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false

  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://integrator-7032551.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa13quhheibs7SXA698
    client-secret: rdv2yH8vQwOSU4TN_6x-kPNC1SA9bweCAtJtmLFYUty90vPU-TpBUtc1KwmD-yna
    scopes: openid,profile,email,offline_access