server:
  port: 8081

spring:
  application:
    name: UserSERVICES

  datasource:
    url: jdbc:mysql://localhost:3306/msuserservices
    username: root
    password: nic@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
   config:
    import: optional:configserver:http://localhost:8085
# eureka:
#   instance:
#     hostname: localhost
#     prefer-ip-address: false

#   client:
#     register-with-eureka: true
#     fetch-registry: true

#     service-url:
#       defaultZone: http://localhost:8761/eureka
